# Generated by Django 5.2.1 on 2025-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.IntegerField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(max_length=3)),
            ],
        ),
    ]
