# Generated by Django 5.2.1 on 2025-05-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_dataentry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(verbose_name=3),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.IntegerField(verbose_name=10),
        ),
    ]
