# Generated by Django 5.2.1 on 2025-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_dataentry", "0002_alter_student_age_alter_student_roll_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
