# Generated by Django 5.2.1 on 2025-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_dataentry", "0003_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="roll_no",
            field=models.IntegerField(null=True, verbose_name=10),
        ),
    ]
